version: "3.8"
services:
    server:
        build:
            context: src/Legacy/server
            dockerfile: server.Dockerfile
        container_name: server
        depends_on:
            - postgres_2
        volumes:
            - ./:/server
        ports:
            - 8000:8000

    reverse-proxy:
        build:
            context: services/nginx
            dockerfile: nginx.Dockerfile
        depends_on:
            - server
        container_name: reverse-proxy
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 3000:3000

    postgres_2:
        build:
            context: services/postgres
            dockerfile: postgres.Dockerfile
        container_name: postgres_2
        user: 999:999 
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "aladin"
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    mongodb:
        build:
            context: services/mongodb
            dockerfile: mongodb.Dockerfile
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: "aladin"
            MONGO_INITDB_ROOT_PASSWORD: "aladin"
            MONGO_INITDB_DATABASE: "ltidb"
        ports:
            - "27017:27017"
        volumes:
            - "mongodb_data:/bitnami/mongodb"
        restart: unless-stopped

    # maxima:
    #     build:
    #         context: services/maxima
    #         dockerfile: maxima.Dockerfile
    #     container_name: maxima
    #     volumes:
    #         - ./services/maxima/:/worker/

volumes:
    mongodb_data:
    postgres-data:
